name: 'fabric_testing'
version: '1.0.0'
config-version: 2

profile: 'fabric-testing'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  fabric_testing:
    +materialized: table

    stage:
      +schema: stage

seeds:
  +full_refresh: True
  +schema: seed

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["tsql_utils", "dbt_utils"]
