fabric-testing:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DBT_FABRIC_SERVER') }}"
      port: 1433
      database: "{{ env_var('DBT_FABRIC_DATABASE') }}"
      schema: dw
      authentication: ActiveDirectoryPassword
      user: "{{ env_var('DBT_ENV_SECRET_FABRIC_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_FABRIC_PASSWORD') }}"
      threads: 8
      trust_cert: true
      encrypt: false
      retries: 1